export { default as Header } from './Header'
export { default as GamesComponent } from './Body/GamesComponent'
export { default as OfferingComponent } from './Body/OfferingComponent'
export { default as BearVSNavyComponent } from './Body/BearVSNavyComponent'
export { default as PAWComponent } from './Body/PAWComponent'
export { default as RegPAWCardComponent } from './Body/RegPAWCardComponent'
export { default as MissionEconomicsComponent } from './Body/MissionEconomicsComponent'
export { default as GOLDTokensComponent } from './Body/GOLDTokensComponent'
export { default as WarStrategyComponent } from './Body/WarStrategyComponent'
export { default as PAWAuctionComponent } from './Body/PAWAuctionComponent'
export { default as InfoComponent } from './Body/InfoComponent'
export { default as RegEconomicsComponent} from './Body/RegEconomicsComponent'
export { default as Body } from './Body'
export { default as Footer } from './Footer'